theme: osuny
_merge: deep
params:
  plausible: mediationanimalehandicap.mmibordeaux.com
  summary:
    position: hero
  search:
    active: true
  logo:
    header: "/assets/images/logo-white.svg"
    footer: "/assets/images/logo.svg"
