[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/organisations/categories/animaux/moutons/"
to = "/associations/categories/animaux/moutons/"

[[redirects]]
from = "/therapies/animaux/chien/"
to = "/therapies/animaux/chiens/"

[[redirects]]
from = "/organisations/categories/pathologies/"
to = "/associations/categories/pathologies/"

[[redirects]]
from = "/organisations/psychien/"
to = "/associations/psychien/"

[[redirects]]
from = "/matthias-oudart/"
to = "/equipe/matthias-oudart/"

[[redirects]]
from = "/organisations/categories/pathologies/handicaps-cognitifs/"
to = "/associations/categories/pathologies/handicaps-cognitifs/"

[[redirects]]
from = "/organisations/categories/pathologies/troubles-du-spectre-autistique/"
to = "/associations/categories/pathologies/troubles-du-spectre-autistique/"

[[redirects]]
from = "/organisations/categories/publics/adultes/"
to = "/associations/categories/publics/adultes/"

[[redirects]]
from = "/therapies/handicaps-cognitifs/"
to = "/therapies/pathologies/handicaps-cognitifs/"

[[redirects]]
from = "/organisations/categories/animaux/anes/"
to = "/associations/categories/animaux/anes/"

[[redirects]]
from = "/organisations/fondation-frederic-gaillainne/"
to = "/associations/fondation-frederic-gaillanne/"

[[redirects]]
from = "/organisations/chiens-guides-lyon-grand-est/"
to = "/associations/chiens-guides-lyon-grand-est/"

[[redirects]]
from = "/organisations/categories/pathologies/syndrome-de-down/"
to = "/associations/categories/pathologies/syndrome-de-down/"

[[redirects]]
from = "/therapies/diabetes/"
to = "/therapies/pathologies/diabetes/"

[[redirects]]
from = "/cesar-morel-1/"
to = "/equipe/cesar-morel-1/"

[[redirects]]
from = "/organisations/cercle-canin-de-lentre-canin-2-mers/"
to = "/associations/cercle-canin-de-lentre-canin-2-mers/"

[[redirects]]
from = "/organisations/categories/publics/"
to = "/associations/categories/publics/"

[[redirects]]
from = "/organisations/animalsens/"
to = "/associations/animal-et-sens/"

[[redirects]]
from = "/organisations/categories/therapies/cynotherapie/"
to = "/associations/categories/therapies/cynotherapie/"

[[redirects]]
from = "/organisations/kdog-institut-curie/"
to = "/associations/kdog-institut-curie/"

[[redirects]]
from = "/equipe/amelie-savary-tolstoi-1/"
to = "/equipe/amelie-savary-tolstoi/"

[[redirects]]
from = "/organisations/les-chiens-du-silence/"
to = "/associations/les-chiens-du-silence/"

[[redirects]]
from = "/organisations/handichiens/"
to = "/associations/handichiens/"

[[redirects]]
from = "/organisations/categories/therapies/"
to = "/associations/categories/therapies/"

[[redirects]]
from = "/organisations/categories/therapies/equitherapie/"
to = "/associations/categories/therapies/equitherapie/"

[[redirects]]
from = "/organisations/categories/public/adolescents/"
to = "/associations/categories/publics/adolescents/"

[[redirects]]
from = "/organisations/categories/pathologies/diabete/"
to = "/associations/categories/pathologies/diabete/"

[[redirects]]
from = "/organisations/categories/animaux/cochons-d-inde/"
to = "/associations/categories/animaux/cochons-d-inde/"

[[redirects]]
from = "/organisations/categories/animaux/"
to = "/associations/categories/animaux/"

[[redirects]]
from = "/organisations/association-chiens-guides-grand-sud-ouest-alienor-bordeaux/"
to = "/associations/association-chiens-guides-grand-sud-ouest-alienor-bordeaux/"

[[redirects]]
from = "/organisations/equivia/"
to = "/associations/equivia/"

[[redirects]]
from = "/organisations/la-cape/"
to = "/associations/la-cape/"

[[redirects]]
from = "/organisations/categories/pathologies/troubles-psychiques/"
to = "/associations/categories/pathologies/troubles-psychiques/"

[[redirects]]
from = "/organisations/categories/animaux/poules/"
to = "/associations/categories/animaux/poules/"

[[redirects]]
from = "/amelie-savary-tolstoi/"
to = "/equipe/amelie-savary-tolstoi/"

[[redirects]]
from = "/organisations/canidea/"
to = "/associations/canidea/"

[[redirects]]
from = "/organisations/categories/publics/tout-public/"
to = "/associations/categories/publics/tout-public/"

[[redirects]]
from = "/amelie-perrot/"
to = "/equipe/amelie-perrot/"

[[redirects]]
from = "/mael-ledrin/"
to = "/equipe/mael-ledrin/"

[[redirects]]
from = "/organisations/categories/pathologies/handicaps-moteurs/"
to = "/associations/categories/pathologies/handicaps-moteurs/"

[[redirects]]
from = "/projets/"
to = "/therapies/"

[[redirects]]
from = "/organisations/fcapi/"
to = "/associations/fcapi/"

[[redirects]]
from = "/organisations/entre-deux-mers/"
to = "/associations/cercle-canin-de-lentre-canin-2-mers/"

[[redirects]]
from = "/organisations/lempreinte-en-gironde/"
to = "/associations/lempreinte-en-gironde/"

[[redirects]]
from = "/organisations/categories/animaux/chevaux/"
to = "/associations/categories/animaux/chevaux/"

[[redirects]]
from = "/organisations/fondation-frederic-gaillanne/"
to = "/associations/fondation-frederic-gaillanne/"

[[redirects]]
from = "/edouard-fort/"
to = "/equipe/edouard-fort/"

[[redirects]]
from = "/organisations/categories/publics/adolescents/"
to = "/associations/categories/publics/adolescents/"

[[redirects]]
from = "/organisations/categories/publics/enfants/"
to = "/associations/categories/publics/enfants/"

[[redirects]]
from = "/organisations/categories/public/tout-public/"
to = "/associations/categories/publics/tout-public/"

[[redirects]]
from = "/organisations/"
to = "/associations/"

[[redirects]]
from = "/organisations/chiens-mediateurs-et-dutilites/"
to = "/associations/chiens-mediateurs-et-dutilites/"

[[redirects]]
from = "/adrian-delgado/"
to = "/equipe/adrian-delgado/"

[[redirects]]
from = "/organisations/categories/publics/seniors/"
to = "/associations/categories/publics/seniors/"

[[redirects]]
from = "/organisations/categories/animaux/chiens/"
to = "/associations/categories/animaux/chiens/"

[[redirects]]
from = "/organisations/categories/public/"
to = "/associations/categories/publics/"

[[redirects]]
from = "/lea-lafaye/"
to = "/equipe/lea-lafaye/"

[[redirects]]
from = "/organisations/a-leau-terre-neuve-gironde/"
to = "/associations/a-leau-terre-neuve-gironde/"

[[redirects]]
from = "/organisations/categories/public/adultes/"
to = "/associations/categories/publics/adultes/"

[[redirects]]
from = "/organisations/animal-et-sens/"
to = "/associations/animal-et-sens/"

[[redirects]]
from = "/organisations/categories/public/enfants/"
to = "/associations/categories/publics/enfants/"

[[redirects]]
from = "/organisations/categories/pathologies/malentendance/"
to = "/associations/categories/pathologies/malentendance/"

[[redirects]]
from = "/organisations/m-en-rouge/"
to = "/associations/m-en-rouge/"

[[redirects]]
from = "/agathe-lb/"
to = "/equipe/agathe-lb/"

[[redirects]]
from = "/organisations/lempreinte-gironde/"
to = "/associations/lempreinte-en-gironde/"

[[redirects]]
from = "/organisations/acadia/"
to = "/associations/acadia/"

[[redirects]]
from = "/organisations/categories/pathologies/malvoyance/"
to = "/associations/categories/pathologies/malvoyance/"

[[redirects]]
from = "/diogo-rios-minaya/"
to = "/equipe/diogo-rios-minaya/"

[[redirects]]
from = "/organisations/categories/public/seniors/"
to = "/associations/categories/publics/seniors/"

[[redirects]]
from = "/organisations/categories/animaux/lapins/"
to = "/associations/categories/animaux/lapins/"

